### ISSUE TITLE
lambda 

### ISSUE THREAD

**Issue by gimkoon448** [unlearning/python-algorithm#10]
(lambda s: s.isdigit(), my_string) # my_string은 문자열
위 방식으로 코드를 작성하면 문자열을 하나씩 불러와서 
진행을 하게 되는건지 아니면 문자열 전체를 가져오게 되는 건지 헷갈려서 질문 올립니다!!

**Comment by Me1e** [comment]
`filter()`, `map()` 함수의 경우
2번째 인자(`my_string`)가 반복가능(list, 문자열 등등)하다면
`my_string`의 요소 하나하나에
1번째 인자의 함수(`lambda`)를 적용해요.

**Comment by Me1e** [comment]
추가로
`filter()` 함수는 요소 하나하나에 `lambda`를 적용시킨 후 반환값이 `true`인 요소만 모아서 `filter 타입`으로 반환해주고
`map()` 함수는 모든 요소 하나하나에 `lambda`를 적용시킨 `map 타입`의 객체를 반환해요.

**Comment by Me1e** [comment]
즉
`list` 형태로 가져오고 싶으면 `list()` 함수로 감싸줘야 해요.

**Comment by gimkoon448** [comment]
제가 sorted(map(int, filter(lambda s: s.isdigit(), my_string))) 
이런 식으로  list를  제외하고 코드를 작성했는데 
[1, 2, 2, 3, 9] 이런 형식으로 출력이 진행됐습니다
map 함수를 사용하면 기본적으로 리스트의 형식으로 데이터로 저장이 진행되는 건가요???
아니면 sorted라는 함수를 써서 리스트의 형식으로 전환된건가요??

**Comment by gimkoon448** [comment]
찾아본 결과 sorted 함수에서는 딕셔너리, 튜플, 문자열 등에도 적용이 가능하다고 명시되어 있네요

**Comment by gimkoon448** [comment]
sorted 함수를 사용하면 input 자료형에 상관 없이 각 원소들이 정렬된 리스트가 반환됩니다.

(딕셔너리의 경우 key에 대한 정렬이 수행됩니다.) 라고 되어 있습니다

**Comment by Me1e** [comment]
`sorted()` 함수가 `list` 형태로 변환해줍니다.
("CBA"라는 문자열을 넣으면 ["A", "B", "C"]가 반환돼요)
