### ISSUE TITLE
Why merge..

### ISSUE THREAD

**Issue by eunbileeme** [unlearning/python-algorithm#6]
silver branch에 push를 시도하다가 
hint : updates were rejected because a pushed branch tip is behind its remote .. 라는 문구를 마주했습니다.

서치를 통해 추천하는 여러 해결 방법을 시도했습니다.
-1. (git fetch) -> git pull origin silver -> git push (-u) origin silver
-2. git push -f origin silver 

-2.로 시도해서 일시적으로 해결했으나 협업 환경에선 추천하지 않는다는 의견에 따라  다시 -1.로 계속 시도하였습니다.

하지만 해결은 되지 않았고.. 해결하지 못한 현상은 다음과 같습니다.
1) hint : updates were rejected because a pushed branch tip is behind its remote .. 
2) [Merge branch 'silver' of](https://github.com/unlearning/python-algorithm/commit/1699d30c2cf8259d8398bec615b59fc5302167cb) https://github.com/unlearning/python-algorithm

2) 는 현재 silver branch의 상황인데, merge 명령을 내리지 않았음에도 왜 merge가 수행되었는지 궁금합니다.

silver branch의 원격 저장소 및 로컬 저장소를 초기화시키고 재업로드를 하고 싶은데, 더이상 손대기가 두렵네요😅

p.s) 계속해서 수습을 시도했었으나, 혹여나 main(master) branch에 관해 꼬인 내용이 있다면 죄송합니다..😢

**Comment by Me1e** [comment]
질문을 글로 정리해보는 습관은 아주 좋아요
제가 issue를 자주 체크하지 않아서 대답이 늦어지면 단톡방에 편하게 물어봐주세요
